/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * LaravelReactTemplate API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ForgotPasswordBody,
  LoginUserBody,
  RegisterANewUserBody,
  ResendVerificationEmailBody,
  ResetPasswordBody,
  UpdateUserFlagsBody,
  VerifyEmailBody
} from '../api.schemas'



  export const getEndpoints = () => {
/**
 * Register a new user account and send email verification.
 * @summary Register a new user
 */
const registerANewUser = <TData = AxiosResponse<unknown>>(
    registerANewUserBody: RegisterANewUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/register`,
      registerANewUserBody,options
    );
  }
/**
 * Authenticate user with email and password, return authentication token.
 * @summary Login user
 */
const loginUser = <TData = AxiosResponse<unknown>>(
    loginUserBody: LoginUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/login`,
      loginUserBody,options
    );
  }
/**
 * Verify user email address with token from email link.
 * @summary Verify email
 */
const verifyEmail = <TData = AxiosResponse<unknown>>(
    verifyEmailBody: VerifyEmailBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/verify-email`,
      verifyEmailBody,options
    );
  }
/**
 * Send a new verification email to the user.
 * @summary Resend verification email
 */
const resendVerificationEmail = <TData = AxiosResponse<unknown>>(
    resendVerificationEmailBody: ResendVerificationEmailBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/resend-verification-email`,
      resendVerificationEmailBody,options
    );
  }
/**
 * Send password reset email with token.
 * @summary Forgot password
 */
const forgotPassword = <TData = AxiosResponse<unknown>>(
    forgotPasswordBody: ForgotPasswordBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/forgot-password`,
      forgotPasswordBody,options
    );
  }
/**
 * Reset user password with token from email link.
 * @summary Reset password
 */
const resetPassword = <TData = AxiosResponse<unknown>>(
    resetPasswordBody: ResetPasswordBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/reset-password`,
      resetPasswordBody,options
    );
  }
/**
 * Revoke the current authentication token and logout the user.
 * @summary Logout user
 */
const logoutUser = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/logout`,undefined,options
    );
  }
/**
 * Get a new authentication token.
 * @summary Refresh token
 */
const refreshToken = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/refresh-token`,undefined,options
    );
  }
/**
 * Get the authenticated user's profile information.
 * @summary Get current user
 */
const getCurrentUser = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/user`,options
    );
  }
/**
 * Get high-level user statistics for the admin dashboard.
Only admins can access this endpoint.
 * @summary Admin dashboard info
 */
const adminDashboardInfo = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/info`,options
    );
  }
/**
 * Get a list of all registered users. Only admins can access this endpoint.
 * @summary List all users
 */
const listAllUsers = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users`,options
    );
  }
/**
 * Update the is_admin and/or is_deactivated flags for a user. Only admins can access this endpoint.
An admin cannot remove their own admin status.
 * @summary Update user flags
 */
const updateUserFlags = <TData = AxiosResponse<unknown>>(
    id: number,
    updateUserFlagsBody?: UpdateUserFlagsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users/${id}`,
      updateUserFlagsBody,options
    );
  }
/**
 * Resend the verification email for a specific user by ID.
Only admins can access this endpoint.
 * @summary Resend verification email for user (admin)
 */
const resendVerificationEmailForUseradmin = <TData = AxiosResponse<unknown>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users/${id}/resend-verification-email`,undefined,options
    );
  }
return {registerANewUser,loginUser,verifyEmail,resendVerificationEmail,forgotPassword,resetPassword,logoutUser,refreshToken,getCurrentUser,adminDashboardInfo,listAllUsers,updateUserFlags,resendVerificationEmailForUseradmin}};
export type RegisterANewUserResult = AxiosResponse<unknown>
export type LoginUserResult = AxiosResponse<unknown>
export type VerifyEmailResult = AxiosResponse<unknown>
export type ResendVerificationEmailResult = AxiosResponse<unknown>
export type ForgotPasswordResult = AxiosResponse<unknown>
export type ResetPasswordResult = AxiosResponse<unknown>
export type LogoutUserResult = AxiosResponse<unknown>
export type RefreshTokenResult = AxiosResponse<unknown>
export type GetCurrentUserResult = AxiosResponse<unknown>
export type AdminDashboardInfoResult = AxiosResponse<unknown>
export type ListAllUsersResult = AxiosResponse<unknown>
export type UpdateUserFlagsResult = AxiosResponse<unknown>
export type ResendVerificationEmailForUseradminResult = AxiosResponse<unknown>
