/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * LaravelReactTemplate API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  HealthCheckEndpoint200
} from '../api.schemas'



  export const getSystem = () => {
/**
 * Returns the current API availability status.
 * @summary Health check endpoint.
 */
const healthCheckEndpoint = <TData = AxiosResponse<HealthCheckEndpoint200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/health`,options
    );
  }
return {healthCheckEndpoint}};
export type HealthCheckEndpointResult = AxiosResponse<HealthCheckEndpoint200>
