/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * LaravelReactTemplate API Documentation
 * OpenAPI spec version: 1.0.0
 */
export type HealthCheckEndpoint200 = {
  message?: string;
  status?: string;
};

export type UpdateUserFlagsBody = {
  /** Set whether the user is an admin. */
  is_admin?: boolean;
  /** Set whether the user is deactivated. */
  is_deactivated?: boolean;
};

export type ListAllUsers401 = {
  message?: string;
};

export type AdminDashboardInfo401 = {
  message?: string;
};

export type GetCurrentUser401 = {
  message?: string;
};

export type ResetPasswordBody = {
  /** Must be a valid email address. The <code>email</code> of an existing record in the users table. */
  email: string;
  /** Must be at least 8 characters. */
  password: string;
  token: string;
};

export type ForgotPasswordBody = {
  /** Must be a valid email address. The <code>email</code> of an existing record in the users table. */
  email: string;
};

export type ResendVerificationEmailBody = {
  /** Must be a valid email address. The <code>email</code> of an existing record in the users table. */
  email: string;
};

export type VerifyEmailBody = {
  /** Must be a valid email address. The <code>email</code> of an existing record in the users table. */
  email: string;
  token: string;
};

export type LoginUserBody = {
  /** Must be a valid email address. */
  email: string;
  password: string;
};

export type RegisterANewUserBody = {
  /** Must be a valid email address. Must not be greater than 255 characters. */
  email: string;
  /** Must not be greater than 255 characters. */
  name: string;
  /** Must be at least 8 characters. */
  password: string;
};

